# Site settings
title: Giannis Miragias Personal  
description: Giannis Miragias Portfolio
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: John Miragias 
user_description: Hello my name is Giannis, I like programming, art and stuff.
user_title: Software Developer
email: ioannis8@hotmail.com
twitter_username: lorem_ipsum
github_username:  miragias
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
