# Site settings
title: Giannis Miragias Personal  
description: Giannis Miragias Portfolio
nothing: nothing
#baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: John Miragias 
user_description: Hello my name is Giannis, software engineer, aspiring 3d artist & tech enthusiast by night. My greatest passions are game development, low level engine programming, algorithms, optimizing code and math. I enjoy tinkering with new technologies/languages/frameworks and I <3 functional approach in software development and clean testable code. I work well with people, and have great communication skills.
user_title: Software Engineer
email: ioannis8@hotmail.com
github_username:  miragias

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
